In [1]:
import numpy as np

## numpy array

In [2]:
myList = [20,30,40]
type(myList)

list

In [4]:
np.array(myList)

array([20, 30, 40])

In [5]:
type(np.array(myList))

numpy.ndarray

In [7]:
matrixList = [[10,20,30],[20,30,40],[30,40,50]]
matrixList[1][0]

20

In [8]:
#numpy listesine çevirelim

np.array(matrixList)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

In [9]:
np.array(matrixList)[1][0]

20

range ile kısayoldan dizi üretebildigimiz gibi np'nin de kendi metotları var

## arange

In [11]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
np.arange(0,10) #yani illa diziye gerek yok

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

## zeros , ones

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
np.ones((6,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## linspace

In [20]:
np.linspace(0,20,7) # 0 ile 20 arasında öyle bir 7 sayi bul ki eşit artsın 20 dahil

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        ])

In [21]:
np.linspace(0,20,9)

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. ])

In [22]:
np.linspace(0,100,100)

array([  0.        ,   1.01010101,   2.02020202,   3.03030303,
         4.04040404,   5.05050505,   6.06060606,   7.07070707,
         8.08080808,   9.09090909,  10.1010101 ,  11.11111111,
        12.12121212,  13.13131313,  14.14141414,  15.15151515,
        16.16161616,  17.17171717,  18.18181818,  19.19191919,
        20.2020202 ,  21.21212121,  22.22222222,  23.23232323,
        24.24242424,  25.25252525,  26.26262626,  27.27272727,
        28.28282828,  29.29292929,  30.3030303 ,  31.31313131,
        32.32323232,  33.33333333,  34.34343434,  35.35353535,
        36.36363636,  37.37373737,  38.38383838,  39.39393939,
        40.4040404 ,  41.41414141,  42.42424242,  43.43434343,
        44.44444444,  45.45454545,  46.46464646,  47.47474747,
        48.48484848,  49.49494949,  50.50505051,  51.51515152,
        52.52525253,  53.53535354,  54.54545455,  55.55555556,
        56.56565657,  57.57575758,  58.58585859,  59.5959596 ,
        60.60606061,  61.61616162,  62.62626263,  63.63

In [23]:
np.linspace(1,100,100)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

## eye

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## random 

In [26]:
np.random.randn(3) #normal dağılıma uygun veriler çıkarmaya çalışır

array([-1.25942019, -0.166476  ,  1.43542357])

In [29]:
np.random.randn(3,3)

array([[ 0.65145733, -0.82929037,  2.27484152],
       [-0.49261733, -0.45849153,  1.53263233],
       [ 0.92047293,  0.20756045,  0.28760384]])

In [30]:
#tek bir deger icin 
np.random.randint(1,10)

7

In [31]:
np.random.randint(1,300,5) #sonuncusu sayisini belirtir

array([ 44, 260, 109, 263, 248])

# nparraylerin Kendi Metotları

In [34]:
np.arange(0,30).reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [35]:
np.arange(0,30).max().reshape(1,1)

array([[29]])

In [36]:
np.random.randint(1,1000,334).max()

996

In [38]:
a = np.random.randint(1,1000,334) # bir degiskene atayıp onun üstünden işlem yapalım

In [39]:
a.argmax() #indexini verir

296

In [40]:
a.argmin()

233

**kendi attribute'ları**

In [42]:
np.arange(0,30).reshape(3,10).shape

(3, 10)

reshape() metodu inplace degildir

In [46]:
myArray = np.arange(0,15)
myArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [44]:
myArray[5]

5

In [45]:
myArray[3:5]

array([3, 4])

In [47]:
myArray[3:8] = -5 #degerleri -5 yapar belirtilen

In [48]:
myArray

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [50]:
myArray = myArray -5  

In [51]:
myArray

array([ -5,  -4,  -3, -10, -10, -10, -10, -10,   3,   4,   5,   6,   7,
         8,   9])

**önemli**

In [52]:
baskaDizi= np.arange(0,24)

In [53]:
slicingDizisi = baskaDizi[4:9]

In [57]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [55]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

bütün elemanları değiştirmek

slicingDizisi = 700 yaparsak bunu bir degisken olarak algılar ve slicingDizisi artık bir degeri 700 olan int degisken olur 
bunun icin asagıdaki yöntemi yaparsak bunun array oldugunu algılayarak yapar

In [58]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [60]:
slicingDizisi[:]

array([4, 5, 6, 7, 8])

In [61]:
slicingDizisi[:] = 700 #bütün elemanları donusturmesi gerektigini anlar

In [62]:
slicingDizisi

array([700, 700, 700, 700, 700])

**buraya dikkat** 

slicingDizisini baskadiziden 4,5,6,7,8 slice ederek almıştık. simdi bakalım başka diziye

In [63]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

slicing ile aldığımız dizi üzerindeki işlemler onu nereden aldıysak onu da etklier bunun önüne geçmek için

**orjinalini degistirmemek icin**

In [64]:
ornekDizi = np.arange(0,24)
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [69]:
ornekDiziKopyasi = ornekDizi.copy()

In [70]:
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [71]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [72]:
onrekDiziKopyasiSlicing = ornekDiziKopyasi[3:6]
onrekDiziKopyasiSlicing

array([3, 4, 5])

In [73]:
onrekDiziKopyasiSlicing[:] = 800

In [74]:
onrekDiziKopyasiSlicing

array([800, 800, 800])

In [76]:
ornekDiziKopyasi

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [77]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

herhangi bir diziden bir şey alıp onu işleyecek ve bu değişikliklerin orjinal diziyi etkilemesini istemiyorsak böyle davranmalıyız

# matrix

In [78]:
benimListem = [[10,20,30],[20,30,40],[40,50,60]]
benimMatrixDizim = np.array(benimListem)
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [79]:
benimMatrixDizim[0]

array([10, 20, 30])

In [80]:
benimMatrixDizim[1][2]

40

In [81]:
benimMatrixDizim[0][2] #ilki satir ikincisi sütun

30

In [82]:
benimMatrixDizim[0,2] #ikisi de ayni sey

30

In [85]:
benimMatrixDizim[1:] 

array([[20, 30, 40],
       [40, 50, 60]])

In [86]:
benimMatrixDizim[1:,2]

array([40, 60])

In [87]:
yeniMatrix = np.arange(0,25)

In [94]:
yeniMatrix = yeniMatrix.reshape(5,-1)

In [95]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [97]:
yeniMatrix[[0,2,3]][2]

array([15, 16, 17, 18, 19])

In [98]:
yeniMatrix[[0,2,3]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [99]:
#index yerine liste vermek

## operasyonlar

In [114]:
yeniBirDizi = np.arange(1,100)

In [115]:
yeniBirDizi

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [116]:
a = np.random.shuffle(yeniBirDizi)

In [117]:
yeniBirDizi

array([ 6, 64, 84, 18,  5, 26, 32, 71, 79,  2, 48, 96, 27, 94,  1, 66, 74,
       85, 98,  7, 56, 86, 75, 77, 76, 91, 51, 50, 28, 19, 93, 78, 31,  4,
       13, 44, 46, 16, 22, 82, 23, 12, 65, 68, 54, 35, 14, 89, 69, 47, 42,
       21, 80, 87, 45, 30, 62, 43, 17, 29, 88, 81, 40, 39, 73, 33, 36, 52,
       97, 24, 37, 57, 41, 34, 99, 60, 90, 15, 92, 55, 59, 49, 83,  9, 70,
        3,  8, 95, 72, 67, 58, 11, 10, 25, 53, 20, 63, 38, 61])

In [119]:
b = yeniBirDizi > 24 

hicbir donguye ihtiyac duymadan tek satir ile sonucları boolean olarak dondurdu

In [120]:
b

array([False,  True,  True, False, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True, False, False,  True,
        True, False, False,  True, False, False,  True,  True,  True,
        True, False,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True, False,  True, False, False,  True,  True,  True,
        True, False, False,  True,  True, False,  True,  True,  True])

In [121]:
yeniBirDizi > 100

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

**önemli numpy dizisine koseli parantez icerisinde bir kosul verdigimizde sadece True elemanları geri dondurud**

In [129]:
yeniBirDizi[b]

array([64, 84, 26, 32, 71, 79, 48, 96, 27, 94, 66, 74, 85, 98, 56, 86, 75,
       77, 76, 91, 51, 50, 28, 93, 78, 31, 44, 46, 82, 65, 68, 54, 35, 89,
       69, 47, 42, 80, 87, 45, 30, 62, 43, 29, 88, 81, 40, 39, 73, 33, 36,
       52, 97, 37, 57, 41, 34, 99, 60, 90, 92, 55, 59, 49, 83, 70, 95, 72,
       67, 58, 25, 53, 63, 38, 61])

sadece 24'ten büyük elemanları geri döndürdü

In [131]:
yeniBirDizi[b]

array([64, 84, 26, 32, 71, 79, 48, 96, 27, 94, 66, 74, 85, 98, 56, 86, 75,
       77, 76, 91, 51, 50, 28, 93, 78, 31, 44, 46, 82, 65, 68, 54, 35, 89,
       69, 47, 42, 80, 87, 45, 30, 62, 43, 29, 88, 81, 40, 39, 73, 33, 36,
       52, 97, 37, 57, 41, 34, 99, 60, 90, 92, 55, 59, 49, 83, 70, 95, 72,
       67, 58, 25, 53, 63, 38, 61])

In [132]:
yeniBirDizi[yeniBirDizi>95]

array([96, 98, 97, 99])

In [133]:
#calısma mantıgı
yeniBirDizi>95

array([False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [134]:
yeniBirDizi[[False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False]]

array([96, 98, 97, 99])

In [135]:
sonDizi = np.arange(0,24)

In [136]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [137]:
sonDizi + sonDizi + sonDizi

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69])

In [138]:
sonDizi * 3 

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69])

In [139]:
sonDizi / sonDizi

<ipython-input-139-20a5ae775714>:1: RuntimeWarning: invalid value encountered in true_divide
  sonDizi / sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

normalde 0'a bolerken hata verir ama burada nan yapar

In [140]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [141]:
np.sqrt(sonDizi).max() #?

4.795831523312719

In [142]:
np.max(np.sqrt(sonDizi)) #?

4.795831523312719